language: node_js
node_js:
  - "stable"
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  - npm install -g sequelize-cli
  - npm run migrate
after_success:
  - npm run coverage
after_script: 
  - nyc report --reporter=text-lcov | coveralls
services:
  - postgresql

